#!/bin/bash

set -u

pb_ver="0.1"

pb_help()
{
    echo "panblog version $pb_ver"
    echo
    echo "valid commands:"
    echo "   write   - create a new blog entry"
    echo "   edit    - edit a draft entry"
    echo "   rewrite - edit a published (non-draft) entry"
    echo "   pub     - publish all articles to preview dir"
    echo "   push    - publish stuff to production server via git push"
    echo "   help    - show this message"
    echo
}


# Turn paths and human-readable stuff into mostly-safe strings
# for filenames and stuff
pb_safestring(){
    echo "$1" | sed 's/ /_/g;s/[?:\/\\]//g;'
}

# Check if entry is to be published or is still in a draft state
pb_entry_type()
{
    if $(head -7 "$1" | grep -i --quiet DRAFT); then
        echo "draft"
    else
        echo "published"
    fi
}



if [[ -f pb.conf ]]; then
    echo "Found config file: pb.conf"
else
    if [ $# -eq 1 ]; then
        case $1 in
            "-h") pb_help;;
            "help") pb_help;;
            *) ;;
        esac
        exit 0
    else
        echo "Config file not foud: pb.conf"
        echo "run pb-create first"
        exit 0
    fi
    
fi

source pb.conf


# Print config from pb.conf
pb_show_config()
{
    echo "Blog: $pb_title"
    echo "Author: $pb_author"
}

# Check if we can publish
pb_check_state()
{
    errcode=0
    if  [ `ls -1 $pb_srcdir*md 2>/dev/null | wc -l` -eq 0 ]; then
        echo "No markdown files. use 'pb write' to create something"
        errcode=1
    else
        pb_mdfiles=("$(ls -r $pb_srcdir*.md)")
    fi

    if [ $errcode -ne 0 ]; then
        echo "Exiting..."
        exit 0
    fi
}


# Publish all of the things
# $1 = [prev|prod] for previw or production mode
# production mode should only be used via the post-receive hook
pb_pub()
{
    pb_check_state

    case $1 in
        "prev") target_dir=$pb_prev_pubroot;;
        "prod") target_dir=$pb_prod_pubroot;;
        *) echo "unknown publication target"
           exit 0 ;;
    esac

    # track what to put in the index page
    indexables=()

    # TODO: track what files are allowed to exist, and remove unallowed files from production/preview
    existables=()
    for mdf in ${pb_mdfiles[@]}; do
        htf=$target_dir${mdf%.md}.html
        if [ $(pb_entry_type $mdf) == "draft" ]; then
            if [ "$1" == "prev" ]; then
                pandoc -o "$htf" "$mdf" $pb_pandoc_args --template "$pb_tmpl_entry_html"
                echo "DRAFT: $mdf -> $htf"
            fi
        else
            mdf_date=$(head -5 "$mdf" | grep -i 'date:')
            mdf_date=${mdf_date#"date:"}
            indexables[${#indexables[@]}]="$mdf_date,$mdf,${htf##*/}"
            if [ "$mdf" -nt "$htf" ]; then
                echo "UP:    $mdf -> $htf"
                pandoc -o "$htf" "$mdf" $pb_pandoc_args --template "$pb_tmpl_entry_html"
            elif [ $pb_verbose -ne 0 ]; then
                echo "CURR:  $mdf -- $htf"
            fi
        fi
    done

    # Sort entries so they go in reverse-date order on the index page
    IFS=$'\n' idxabl_sorted=($(sort -r <<<"${indexables[*]}")); unset IFS

    ## Make Index Page
    cat $pb_tmpl_index |\
        sed "s/__TITLE__/$pb_title/;" |\
        sed "s/__AUTHOR__/$pb_author/;" > "$pb_temp_index"
    for idxabl in ${idxabl_sorted[@]}; do
        IFS="," read -r -a idxar <<< "$idxabl"; unset IFS
        mdf_title=$(head -5 "${idxar[1]}" | grep -i 'title:')
        mdf_title=${mdf_title#"title:"}
        echo "[${idxar[0]} -$mdf_title](./${idxar[2]})" >> "$pb_temp_index"
        echo >> "$pb_temp_index"
    done

    pandoc -o "$target_dir/index.html" "$pb_temp_index" $pb_pandoc_args --template "$pb_tmpl_index_html"
    rm "$pb_temp_index"

    cp -vu "$pb_srcdir/style.css" "$target_dir/"

    echo "Copying updated media"
    if hash rsync 2>>/dev/null; then
       rsync -vruc --delete "$pb_srcdir/$pb_relmediadir/" "$target_dir/$pb_relmediadir"
    else
       cp -vru "$pb_srcdir/$pb_relmediadir" "$target_dir/"
    fi
}

# Creat a new timestamped article named for the article title
pb_write()
{
  entry_date="$(date +'%Y-%m-%d-%H-%M')"
  echo "Enter article title:"
  read entry_title
  safe_title=$(pb_safestring "$entry_title")
  filename="$entry_date-$safe_title"
  cat "$pb_tmpl_entry" |\
      sed "s/__TITLE__/$entry_title/;" |\
      sed "s/__AUTHOR__/$pb_author/;" |\
      sed "s/__DATE__/$entry_date/;" > "$filename.md"
  $pb_editor "$filename.md"
}

# Print a list of 'editables', user selects which one by index
# $1 = type of editable (draft, published)
pb_edit()
{
    pb_check_state
    editables=()
    for mdf in ${pb_mdfiles[@]}; do
        if [ $(pb_entry_type $mdf) == $1 ]; then
            echo "${#editables[@]}: $mdf" # TODO get article  titles
            editables[${#editables[@]}]=$mdf
        fi
    done
    read etbl_idx
    if ! [[ "$etbl_idx" =~ ^[0-9]+$ ]]; then
        echo "Positive integer input only"
    elif [ "$etbl_idx" -lt 0 ]; then
        echo "Positive integer input only"
    elif [ "$etbl_idx" -le ${#editables[@]} ]; then
        $pb_editor "${editables[$etbl_idx]}"
    else
        echo "Selected index does not exist"
    fi
}

pb_show_config

if [ $# -ne 1 ]; then
    pb_help
    exit 0
fi

case $1 in
    "write") pb_write;;
    "edit") pb_edit draft;;
    "rewrite") pb_edit published;;
    "pub") pb_pub prev;;
    "-h") pb_help;;
    *) pb_help;;
esac
