#!/bin/bash

set -u

echo
echo

repo_dir="$(pwd)"
repo_name="${repo_dir##*/}"
pb_tmp="$HOME/pb/$repo_name"

mkdir -p "$pb_tmp"

cd "$pb_tmp"

git clone "$repo_dir" ./ 2>/dev/null

OLD_GIT_DIR="$GIT_DIR"
export GIT_DIR="$(pwd)/.git"
git pull origin master
GIT_DIR="$OLD_GIT_DIR"

"$HOME/.local/bin/pb" prod
