#!/bin/bash

set -u

repo_dir="$(pwd)/../../"
pb_tmp="/tmp/pb/"
mkdir -p "$pb_tmp"

echo $(pwd)

git --work-tree="$pb_tmp" --git-dir="$repo_dir" checkout -f

pushd "$pb_tmp"
echo $(pwd)
pb

popd
rm -rf "$pb_tmp"



